// Predefined subtitle-customization presets (part B: vintage..forest). Pure data.
import { defaultCustomization } from './defaultCustomization';

export const presetsPartB = {
      vintage: {
        ...defaultCustomization,
        fontFamily: "'Playfair Display', serif",
        fontSize: 32,
        fontWeight: 400,
        textColor: '#f4e4bc',
        backgroundColor: '#8b4513',
        backgroundOpacity: 85,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#daa520',
        textShadowEnabled: true,
        textShadowColor: '#654321',
        textShadowBlur: 8,
        letterSpacing: 1,
        strokeEnabled: false,
        preset: 'vintage'
      },
      comic: {
        ...defaultCustomization,
        fontFamily: "'Bangers', cursive",
        fontSize: 36,
        fontWeight: 400,
        textColor: '#ffffff',
        backgroundColor: '#ff6b35',
        backgroundOpacity: 90,
        borderRadius: 20,
        borderWidth: 4,
        borderColor: '#000000',
        strokeEnabled: true,
        strokeWidth: 3,
        strokeColor: '#000000',
        textShadowEnabled: true,
        textShadowColor: '#ff0000',
        textShadowBlur: 5,
        preset: 'comic'
      },
      horror: {
        ...defaultCustomization,
        fontFamily: "'Nosifer', cursive",
        fontSize: 34,
        fontWeight: 400,
        textColor: '#8b0000',
        backgroundColor: '#000000',
        backgroundOpacity: 95,
        borderRadius: 5,
        glowEnabled: true,
        glowColor: '#8b0000',
        glowIntensity: 30,
        textShadowEnabled: true,
        textShadowColor: '#ff0000',
        textShadowBlur: 20,
        textShadowOffsetY: 5,
        letterSpacing: 2,
        strokeEnabled: false,
        preset: 'horror'
      },
      luxury: {
        ...defaultCustomization,
        fontFamily: "'Playfair Display', serif",
        fontSize: 35,
        fontWeight: 400,
        textColor: '#ffd700',
        backgroundColor: '#1a1a1a',
        backgroundOpacity: 80,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ffd700',
        textShadowEnabled: true,
        textShadowColor: '#000000',
        textShadowBlur: 10,
        letterSpacing: 2,
        lineHeight: 1.4,
        strokeEnabled: false,
        preset: 'luxury'
      },
      kawaii: {
        ...defaultCustomization,
        fontFamily: "'Comfortaa', cursive",
        fontSize: 30,
        fontWeight: 600,
        textColor: '#ff69b4',
        backgroundColor: '#ffffff',
        backgroundOpacity: 85,
        borderRadius: 25,
        borderWidth: 3,
        borderColor: '#ff69b4',
        textShadowEnabled: true,
        textShadowColor: '#ffb6c1',
        textShadowBlur: 8,
        strokeEnabled: false,
        preset: 'kawaii'
      },
      grunge: {
        ...defaultCustomization,
        fontFamily: "'Righteous', cursive",
        fontSize: 32,
        fontWeight: 400,
        textColor: '#ffffff',
        backgroundColor: '#2f2f2f',
        backgroundOpacity: 90,
        borderRadius: 0,
        strokeEnabled: true,
        strokeWidth: 2,
        strokeColor: '#000000',
        textShadowEnabled: true,
        textShadowColor: '#000000',
        textShadowBlur: 15,
        textShadowOffsetY: 3,
        letterSpacing: 1,
        preset: 'grunge'
      },
      corporate: {
        ...defaultCustomization,
        fontFamily: "'Open Sans', sans-serif",
        fontSize: 28,
        fontWeight: 400,
        textColor: '#2c3e50',
        backgroundColor: '#ecf0f1',
        backgroundOpacity: 90,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#bdc3c7',
        textShadowEnabled: false,
        letterSpacing: 0.5,
        lineHeight: 1.3,
        strokeEnabled: false,
        preset: 'corporate'
      },
      anime: {
        ...defaultCustomization,
        fontFamily: "'Nunito', sans-serif",
        fontSize: 32,
        fontWeight: 700,
        textColor: '#ffffff',
        backgroundColor: '#ff6b9d',
        backgroundOpacity: 85,
        borderRadius: 15,
        borderWidth: 2,
        borderColor: '#ffffff',
        strokeEnabled: true,
        strokeWidth: 1,
        strokeColor: '#ff1493',
        textShadowEnabled: true,
        textShadowColor: '#ff1493',
        textShadowBlur: 8,
        preset: 'anime'
      },
      vaporwave: {
        ...defaultCustomization,
        fontFamily: "'Orbitron', sans-serif",
        fontSize: 34,
        fontWeight: 300,
        gradientEnabled: true,
        gradientColorStart: '#ff00ff',
        gradientColorEnd: '#00ffff',
        gradientDirection: '45deg',
        backgroundColor: '#1a0033',
        backgroundOpacity: 90,
        borderRadius: 0,
        glowEnabled: true,
        glowColor: '#ff00ff',
        glowIntensity: 20,
        letterSpacing: 4,
        textTransform: 'uppercase',
        strokeEnabled: false,
        preset: 'vaporwave'
      },
      steampunk: {
        ...defaultCustomization,
        fontFamily: "'Cinzel', serif",
        fontSize: 30,
        fontWeight: 600,
        textColor: '#cd853f',
        backgroundColor: '#2f1b14',
        backgroundOpacity: 90,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#8b4513',
        textShadowEnabled: true,
        textShadowColor: '#000000',
        textShadowBlur: 12,
        letterSpacing: 1,
        strokeEnabled: false,
        preset: 'steampunk'
      },
      noir: {
        ...defaultCustomization,
        fontFamily: "'Bebas Neue', sans-serif",
        fontSize: 36,
        fontWeight: 400,
        textColor: '#ffffff',
        backgroundColor: '#000000',
        backgroundOpacity: 95,
        borderRadius: 0,
        textShadowEnabled: true,
        textShadowColor: '#333333',
        textShadowBlur: 20,
        textShadowOffsetY: 8,
        letterSpacing: 3,
        textTransform: 'uppercase',
        strokeEnabled: false,
        preset: 'noir'
      },
      pastel: {
        ...defaultCustomization,
        fontFamily: "'Quicksand', sans-serif",
        fontSize: 28,
        fontWeight: 500,
        textColor: '#6b5b95',
        backgroundColor: '#f8f8ff',
        backgroundOpacity: 85,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#dda0dd',
        textShadowEnabled: true,
        textShadowColor: '#e6e6fa',
        textShadowBlur: 6,
        strokeEnabled: false,
        preset: 'pastel'
      },
      bold: {
        ...defaultCustomization,
        fontFamily: "'Anton', sans-serif",
        fontSize: 42,
        fontWeight: 400,
        textColor: '#ffffff',
        backgroundColor: '#000000',
        backgroundOpacity: 90,
        borderRadius: 5,
        strokeEnabled: true,
        strokeWidth: 4,
        strokeColor: '#ff0000',
        textShadowEnabled: true,
        textShadowColor: '#ff0000',
        textShadowBlur: 10,
        letterSpacing: 2,
        textTransform: 'uppercase',
        preset: 'bold'
      },
      sketch: {
        ...defaultCustomization,
        fontFamily: "'Kalam', cursive",
        fontSize: 30,
        fontWeight: 400,
        textColor: '#2c3e50',
        backgroundColor: '#ffffff',
        backgroundOpacity: 80,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#34495e',
        strokeEnabled: true,
        strokeWidth: 1,
        strokeColor: '#7f8c8d',
        preset: 'sketch'
      },
      glitch: {
        ...defaultCustomization,
        fontFamily: "'Courier New', monospace",
        fontSize: 32,
        fontWeight: 700,
        textColor: '#00ff00',
        backgroundColor: '#000000',
        backgroundOpacity: 95,
        borderRadius: 0,
        glowEnabled: true,
        glowColor: '#00ff00',
        glowIntensity: 35,
        textShadowEnabled: true,
        textShadowColor: '#ff0000',
        textShadowBlur: 8,
        textShadowOffsetY: 2,
        letterSpacing: 3,
        textTransform: 'uppercase',
        strokeEnabled: false,
        preset: 'glitch'
      },
      royal: {
        ...defaultCustomization,
        fontFamily: "'Cinzel', serif",
        fontSize: 34,
        fontWeight: 600,
        textColor: '#ffd700',
        backgroundColor: '#4b0082',
        backgroundOpacity: 90,
        borderRadius: 10,
        borderWidth: 3,
        borderColor: '#ffd700',
        textShadowEnabled: true,
        textShadowColor: '#000000',
        textShadowBlur: 15,
        letterSpacing: 2,
        lineHeight: 1.4,
        strokeEnabled: false,
        preset: 'royal'
      },
      sunset: {
        ...defaultCustomization,
        fontFamily: "'Poppins', sans-serif",
        fontSize: 32,
        fontWeight: 500,
        gradientEnabled: true,
        gradientColorStart: '#ff7e5f',
        gradientColorEnd: '#feb47b',
        gradientDirection: '135deg',
        backgroundColor: '#2c1810',
        backgroundOpacity: 75,
        borderRadius: 15,
        textShadowEnabled: true,
        textShadowColor: '#8b4513',
        textShadowBlur: 10,
        strokeEnabled: false,
        preset: 'sunset'
      },
      ocean: {
        ...defaultCustomization,
        fontFamily: "'Merriweather', serif",
        fontSize: 30,
        fontWeight: 400,
        gradientEnabled: true,
        gradientColorStart: '#667eea',
        gradientColorEnd: '#764ba2',
        gradientDirection: '90deg',
        backgroundColor: '#1e3c72',
        backgroundOpacity: 80,
        borderRadius: 12,
        textShadowEnabled: true,
        textShadowColor: '#0f1419',
        textShadowBlur: 8,
        strokeEnabled: false,
        preset: 'ocean'
      },
      forest: {
        ...defaultCustomization,
        fontFamily: "'Lora', serif",
        fontSize: 28,
        fontWeight: 400,
        textColor: '#90ee90',
        backgroundColor: '#2d5016',
        backgroundOpacity: 85,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#228b22',
        textShadowEnabled: true,
        textShadowColor: '#006400',
        textShadowBlur: 12,
        letterSpacing: 0.5,
        strokeEnabled: false,
        preset: 'forest'
      }
};
