/**
 * React App Configuration
 * Generated automatically from centralized server configuration
 * Do not edit this file manually - run npm run setup:react-env instead
 */

// Port configurations from environment variables
export const PORTS = {
  FRONTEND: parseInt(process.env.REACT_APP_FRONTEND_PORT) || 3030,
  BACKEND: parseInt(process.env.REACT_APP_BACKEND_PORT) || 3031,
  WEBSOCKET: parseInt(process.env.REACT_APP_WEBSOCKET_PORT) || 3032,
  VIDEO_RENDERER: parseInt(process.env.REACT_APP_VIDEO_RENDERER_PORT) || 3033,
  VIDEO_RENDERER_FRONTEND: parseInt(process.env.REACT_APP_VIDEO_RENDERER_FRONTEND_PORT) || 3034,
  NARRATION: parseInt(process.env.REACT_APP_NARRATION_PORT) || 3035,
  CHATTERBOX: parseInt(process.env.REACT_APP_CHATTERBOX_PORT) || 3036
};

// API Base URLs
export const API_URLS = {
  BACKEND: `http://localhost:${PORTS.BACKEND}`,
  VIDEO_RENDERER: `http://localhost:${PORTS.VIDEO_RENDERER}`,
  NARRATION: `http://localhost:${PORTS.NARRATION}`,
  CHATTERBOX: `http://localhost:${PORTS.CHATTERBOX}`,
  WEBSOCKET: `ws://localhost:${PORTS.WEBSOCKET}`
};

// Environment detection
export const IS_DEVELOPMENT = process.env.NODE_ENV === 'development';
export const IS_PRODUCTION = process.env.NODE_ENV === 'production';

export default {
  PORTS,
  API_URLS,
  IS_DEVELOPMENT,
  IS_PRODUCTION
};
